input_files :=\
	test.shader \
	terrain.shader \
	terrain_test.shader \
	imgui.shader \
	line.shader \
	test_constbuffer.shader \
	test_texture.shader \
	skybox.shader \
#-------------

#input_files := test.shader # just single test

include ../../../../src/sge_shader_compiler.GNUmakefile