input_files :=\
	test.shader \
	terrain.shader \
	terrain_test.shader \
	imgui.shader \
	line.shader \
	test_constbuffer.shader \
	test_texture.shader \
	skybox.shader \
	pbr.shader \
	test_compute_triangles.shader \
	test_compute_triangles_display.shader \
#-------------

# just for single test
#input_files := pbr.shader

include ../../../../src/sge_shader_compiler.GNUmakefile